version: "3.8"
services:
  qr_code_api:
    image: elleined/qca
    container_name: qr_code_api
    ports:
      - "8092:8092"
    networks:
      - qca_network
networks:
  qca_network:
    name: qca_network
    external: false
    ipam:
      driver: default
