version: "3.8"
services:
  qr_code_api:
    image: elleined/qr-code-api
    container_name: qr_code_api
    env_file:
      - .env
    networks:
      - qr_code_api_network
networks:
  qr_code_api_network:
    name: qr_code_api_network
    external: false
    ipam:
      driver: default
